### ISSUE TITLE
Keybind not working for me

### ISSUE THREAD

**Issue by oliverfischer83** [GeorgeArgyrakis/YouAreMuted#1]
Hi, really love that tool, exactly what I was looking for. 

Unfortunately the keybind to mute (CTRL+SHIFT+M) is not working for me. I have a german QWERTZ keyboard, but I also tried the virtual QWERTY US keyboard designs. Could this issue be related to the keyboard layout? 

My system details are ...
Edition: Windows 11 Home
Version: 22H2
OS build: 22621.1194
Language: English (US) language pack
Keyboard layout: German (QUERTZ)

I'm more experienced with the Java eco-system, could you please point me to the source code file, where the keybind is definded?

Thank you in advance.

**Comment by GeorgeArgyrakis** [comment]
@oliverfischer83 Hello, the keybind is defined on MainForm.cs:35 
`HotKeys.RegisterGlobalHotKey(1, this.Handle, Keys.M, NativeMethods.MOD_CONTROL | NativeMethods.MOD_SHIFT);`

**Comment by oliverfischer83** [comment]
Obsolete.
