### ISSUE TITLE
The outline prevents me clicking on anything underneath it: is it possible to make it "transparent" for mouse clicks?

### ISSUE THREAD

**Issue by johnbradley101** [GeorgeArgyrakis/YouAreMuted#3]
The outline is useful as a visual indicator and is helpful when on calls to see the mute status.
However, it prevents me from clicking on anything underneath the outline e.g. like the citrix menu.

![image](https://github.com/GeorgeArgyrakis/YouAreMuted/assets/105434106/1a698cdf-f040-4909-8f7a-883cf4cdddc1)

is there a way to make it transparent to mouse clicks and allow me to click what is directly underneath the outline?

**Comment by andrebian** [comment]
You can reduce line size and set the outline more discrete, I've changed it size and transparency on MainForm.cs.

![image](https://github.com/GeorgeArgyrakis/YouAreMuted/assets/2091739/a3d03959-e964-4324-8ded-ac9b9f32e006)

![image](https://github.com/GeorgeArgyrakis/YouAreMuted/assets/2091739/c0a0a878-e836-44fd-a374-c043411a043a)

**Comment by GeorgeArgyrakis** [comment]
@johnbradley101 as @andrebian wrote you can change the width of the outline on MainForm.cs:42
` statusRects.Add(new ScreenBoundingRectangle() { Color = System.Drawing.Color.Red, LineWidth = 10, Location = screen.Bounds, Opacity = 0.5, Visible = showOutline });` by changing `LineWidth `

Commit 025e156 made outline "transparent to clicks"
