### ISSUE TITLE
it possible to trigger an event when the mutestatus changes?

### ISSUE THREAD

**Issue by johnbradley101** [GeorgeArgyrakis/YouAreMuted#4]
Is it possible to trigger a keyboard shortcut when the mute status changes?

I have a plantronics status indicator light, and it has the option for the colour to be changed manually via   a keyboard shortcut.
It would be great if your app could be used to trigger a pre-defined shortcut key to set the colour of this light.

e.g. 
on MuteON = Ctrl+Alt + A
on MuteOff = Ctrl+Alt + B
etc.

![image](https://github.com/GeorgeArgyrakis/YouAreMuted/assets/105434106/dfd532a8-d7ce-4552-9304-574c2f92c7b2)

**Comment by GeorgeArgyrakis** [comment]
@johnbradley101 you can use these commands
```
System.Windows.Forms.SendKeys.Send("^%Α");  // Ctrl+Alt + A
System.Windows.Forms.SendKeys.Send("^%B");  // Ctrl+Alt + B
```
